version: '3.7'

services:
  nginx:
    image: nginx:alpine
    user: root
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites-available:/etc/nginx/conf.d
      - ./nginx/logs:/var/log/nginx
      - ./goaccess/html:/example.com
    networks:
      - proxy
    ports:
      - mode: host
        protocol: tcp
        published: 80
        target: 80

  goaccess:
    build: ./goaccess
    volumes:
      - ./goaccess/goaccess.conf:/srv/config/goaccess.conf
      - ./goaccess/data:/srv/data
      - ./goaccess/html:/srv/report
      - ./goaccess/GeoLite2-City:/usr/local/share/GeoIP
      - ./nginx/logs:/srv/logs
    environment:
      - TZ=Europe/Sofia
    command: ["--no-global-config", "--config-file=/srv/config/goaccess.conf", "--log-file=/srv/logs/example.com_access.log"]
    deploy:
      mode: replicated
      replicas: 0
      labels:
        - "swarm.cronjob.enable=true"
        - "swarm.cronjob.schedule=*/5 * * * *"
        - "swarm.cronjob.skip-running=false"
      restart_policy:
        condition: none
    depends_on:
      - swarm-cronjob

  swarm-cronjob:
    image: crazymax/swarm-cronjob
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Sofia"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
    deploy:
      placement:
        constraints:
          - node.role == manager
networks:
  proxy:
